AWSTemplateFormatVersion: 2010-09-09
Description: "The Dynamo DB instance for Rentalated account management."
Resources: 
  UserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: email
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: email
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Version
          Value: 1
  RevokedTokensTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: accessToken
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: accessToken
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  UserTable: 
    Value: !Ref UserTable
  RevokedTokensTable:
    Value: !Ref RevokedTokensTable