version: '3'
services:
  flask:
    image: tiangolo/uwsgi-nginx-flask:python3.7
    entrypoint: flask run --host=0.0.0.0 --port=5000
    environment: 
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONPATH=$PYTHONPATH:app/:.venv/lib/python3.7/site-packages
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "5000:5000"
      - "465:465"
    volumes: 
      - ./src:/app