version: '3'
services:
  flask:
    image: tiangolo/uwsgi-nginx-flask:python3.7
    entrypoint: flask run --host=0.0.0.0 --port=80
    environment: 
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONPATH=$PYTHONPATH:app/
    ports:
      - "80:80"
    volumes: 
      - ./src:/app